### PR TITLE
Add missing .bind(this) in BinaryReconstructor.takeBinaryData

### PR DESCRIPTION
**Pull request by AlexanderDzhoganov**

### CODE REVIEW

**Comment by SupremeTechnopriest** [comment]
can we get this merged in?  I ran into the same error.

**Comment by tomcartwrightuk** [comment]
Adding both of you as collaborators so you can merge yourself. If someone could make a `bump socket.io-parser` PR for socket.io-p2p I can get that merged. (I would add you as collaborators but I don't have admin access on the that org)

**Comment by SupremeTechnopriest** [comment]
Thanks!

**Comment by SupremeTechnopriest** [comment]
We will still need you to run `npm publish`.  If you want to add me as a collaborator on npm my username is the same as it is here.

**Pull request merged**
